from mttkinter import mtTkinter as tk
from tkinter import ttk
from InterfaceFn import *
from heidolphFn import *
from milliGATFn import *
from valveFn import *
from watsonFn import *
from sf10Fn import *
#from asiapumpFn import *
from oushishengFn import *
from watsonFn import *
import time
import threading
frame = InterfaceFn()
fr_cmdInt = frame.fr_cmdInt
#parameter
valve_1=valveFn()
valve_2=valveFn()
watson_1=watsonFn()
watson_2=watsonFn()

#endparameter
#init
def autoprog_init():
	global valve_1
	valve_1.valve_init('COM9', 1, frame.lbl_init)
	valve_1.lbl_valve_sta = lbl_valve_1_sta
	global valve_2
	valve_2.valve_init('COM6', 2, frame.lbl_init)
	valve_2.lbl_valve_sta = lbl_valve_2_sta
	global watson_1
	watson_1.watson_init('COM8', 1, frame.lbl_init)
	watson_1.lbl_watson_sta = lbl_watson_1_sta
	global watson_2
	watson_2.watson_init('COM7', 2, frame.lbl_init)
	watson_2.lbl_watson_sta = lbl_watson_2_sta

#endinit
#cmd
def autoprog_start():
	valve_1.valve_go(0, 4, lbl_0)
	valve_2.valve_go(0, 1, lbl_1)
	watson_1.watson_pumping('RL', 0.0, 800, lbl_2)
	watson_1.watson_pumping('RL', 4.4, 400, lbl_3)
	watson_2.watson_pumping('RL', 0.0, 800, lbl_4)
	valve_1.valve_go(0, 2, lbl_5)
	valve_2.valve_go(1260, 3, lbl_6)
	valve_1.valve_go(5, 1,  lbl_7)
	valve_2.valve_go(0, 1,  lbl_8)
	valve_1.valve_go(1, 2,  lbl_9)
	valve_2.valve_go(5, 2,  lbl_10)
	valve_1.valve_go(5, 4,  lbl_11)
	valve_2.valve_go(0, 1,  lbl_12)
	watson_1.watson_pumping('RL', 0.0, 800, lbl_13)
	watson_1.watson_pumping('RL', 4.4, 400, lbl_14)
	valve_1.valve_go(0, 2,  lbl_15)
	valve_2.valve_go(1260, 3, lbl_16)
	valve_1.valve_go(5, 1,  lbl_17)
	valve_2.valve_go(0, 1,  lbl_18)
	valve_1.valve_go(1, 2,  lbl_19)
	valve_2.valve_go(5, 2,  lbl_20)
	valve_1.valve_go(5, 4,  lbl_21)
	valve_2.valve_go(0, 1,  lbl_22)
	watson_1.watson_pumping('RL', 0.0, 800, lbl_23)
	watson_1.watson_pumping('RL', 4.4, 400, lbl_24)
	valve_1.valve_go(0, 2,  lbl_25)
	valve_2.valve_go(1260, 3, lbl_26)
	valve_1.valve_go(5, 1,  lbl_27)
	valve_2.valve_go(0, 1,  lbl_28)
	valve_1.valve_go(1, 2,  lbl_29)
	valve_2.valve_go(5, 2,  lbl_30)
	valve_1.valve_go(5, 4,  lbl_31)
	valve_2.valve_go(0, 1,  lbl_32)
	watson_1.watson_pumping('RL', 0.0, 800, lbl_33)
	watson_1.watson_pumping('RL', 4.4, 400, lbl_34)
	valve_1.valve_go(0, 2,  lbl_35)
	valve_2.valve_go(1260, 3, lbl_36)
	valve_1.valve_go(5, 1,  lbl_37)
	valve_2.valve_go(0, 1,  lbl_38)
	valve_1.valve_go(1, 2,  lbl_39)
	valve_2.valve_go(5, 2,  lbl_40)
	valve_1.valve_go(5, 4,  lbl_41)
	valve_2.valve_go(0, 1,  lbl_42)
	watson_1.watson_pumping('RL', 0.0, 800, lbl_43)
	watson_1.watson_pumping('RL', 4.4, 400, lbl_44)
	valve_1.valve_go(0, 2,  lbl_45)
	valve_2.valve_go(1260, 3, lbl_46)
	valve_1.valve_go(5, 1,  lbl_47)
	valve_2.valve_go(0, 1,  lbl_48)
	valve_1.valve_go(1, 2,  lbl_49)
	valve_2.valve_go(5, 2,  lbl_50)
	valve_1.valve_go(5, 4,  lbl_51)
	valve_2.valve_go(0, 1,  lbl_52)
	watson_1.watson_pumping('RL', 0.0, 800, lbl_53)
	watson_1.watson_pumping('RL', 4.4, 400, lbl_54)
	valve_1.valve_go(0, 2,  lbl_55)
	valve_2.valve_go(1260, 3, lbl_56)
	valve_1.valve_go(5, 1,  lbl_57)
	valve_2.valve_go(0, 1,  lbl_58)
	valve_1.valve_go(1, 2,  lbl_59)
	valve_2.valve_go(5, 2,  lbl_60)
	valve_1.valve_go(5, 4,  lbl_61)
	valve_2.valve_go(0, 1,  lbl_62)
	watson_1.watson_pumping('RL', 0.0, 800, lbl_63)
	watson_1.watson_pumping('RL', 4.4, 400, lbl_64)
	valve_1.valve_go(0, 2,  lbl_65)
	valve_2.valve_go(1260, 3, lbl_66)
	valve_1.valve_go(5, 1,  lbl_67)
	valve_2.valve_go(0, 1,  lbl_68)
	valve_1.valve_go(1, 2,  lbl_69)
	valve_2.valve_go(5, 2,  lbl_70)
	valve_1.valve_go(5, 4,  lbl_71)
	valve_2.valve_go(0, 1,  lbl_72)
	watson_1.watson_pumping('RL', 0.0, 800, lbl_73)
	watson_1.watson_pumping('RL', 4.4, 400, lbl_74)
	valve_1.valve_go(0, 2,  lbl_75)
	valve_2.valve_go(1260, 3, lbl_76)
	valve_1.valve_go(5, 1,  lbl_77)
	valve_2.valve_go(0, 1,  lbl_78)
	valve_1.valve_go(1, 2,  lbl_79)
	valve_2.valve_go(5, 2,  lbl_80)
	valve_1.valve_go(5, 4,  lbl_81)
	valve_2.valve_go(0, 1,  lbl_82)
	watson_1.watson_pumping('RL', 0.0, 800, lbl_83)
	watson_1.watson_pumping('RL', 4.4, 400, lbl_84)
	valve_1.valve_go(0, 2,  lbl_85)
	valve_2.valve_go(1260, 3, lbl_86)
	valve_1.valve_go(5, 1,  lbl_87)
	valve_2.valve_go(0, 1,  lbl_88)
	valve_1.valve_go(1, 2,  lbl_89)
	valve_2.valve_go(5, 2,  lbl_90)
	valve_1.valve_go(5, 4,  lbl_91)
	valve_2.valve_go(0, 1,  lbl_92)
	watson_1.watson_pumping('RL', 0.0, 800, lbl_93)
	watson_1.watson_pumping('RL', 4.4, 400, lbl_94)
	valve_1.valve_go(0, 2,  lbl_95)
	valve_2.valve_go(1260, 3, lbl_96)
	valve_1.valve_go(5, 1,  lbl_97)
	valve_2.valve_go(0, 1,  lbl_98)
	valve_1.valve_go(1, 2,  lbl_99)
	valve_2.valve_go(5, 2,  lbl_100)
	watson_2.watson_stoping('RL', 5.0, lbl_101)
	watson_1.watson_stoping('RL', 0.0, lbl_102)
	autoprog_abort()
#endcmd
#abort
def autoprog_abort():
	valve_1.close()
	valve_2.close()
	watson_1.close()
	watson_2.close()

#endabort
#label
lbl_0 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 1 goes to position 4', anchor = 'w', justify = tk.LEFT)
lbl_0.pack()
lbl_1 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_1.pack()
lbl_2 = tk.Label(fr_cmdInt, width = 75, text = 'After 0.0 min, Watson Marlow 1 pumps anti-clockwise at 800 RPM', anchor = 'w', justify = tk.LEFT)
lbl_2.pack()
lbl_3 = tk.Label(fr_cmdInt, width = 75, text = 'After 4.4 min, Watson Marlow 1 pumps anti-clockwise at 400 RPM', anchor = 'w', justify = tk.LEFT)
lbl_3.pack()
lbl_4 = tk.Label(fr_cmdInt, width = 75, text = 'After 0.0 min, Watson Marlow 2 pumps anti-clockwise at 800 RPM', anchor = 'w', justify = tk.LEFT)
lbl_4.pack()
lbl_5 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_5.pack()
lbl_6 = tk.Label(fr_cmdInt, width = 75, text = 'After 1260 min, Valve 2 goes to position 3', anchor = 'w', justify = tk.LEFT)
lbl_6.pack()
lbl_7 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_7.pack()
lbl_8 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_8.pack()
lbl_9 = tk.Label(fr_cmdInt, width = 75, text = 'After 1 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_9.pack()
lbl_10 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 2 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_10.pack()
lbl_11 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 4', anchor = 'w', justify = tk.LEFT)
lbl_11.pack()
lbl_12 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_12.pack()
lbl_13 = tk.Label(fr_cmdInt, width = 75, text = 'After 0.0 min, Watson Marlow 1 pumps anti-clockwise at 800 RPM', anchor = 'w', justify = tk.LEFT)
lbl_13.pack()
lbl_14 = tk.Label(fr_cmdInt, width = 75, text = 'After 4.4 min, Watson Marlow 1 pumps anti-clockwise at 400 RPM', anchor = 'w', justify = tk.LEFT)
lbl_14.pack()
lbl_15 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_15.pack()
lbl_16 = tk.Label(fr_cmdInt, width = 75, text = 'After 1260 min, Valve 2 goes to position 3', anchor = 'w', justify = tk.LEFT)
lbl_16.pack()
lbl_17 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_17.pack()
lbl_18 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_18.pack()
lbl_19 = tk.Label(fr_cmdInt, width = 75, text = 'After 1 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_19.pack()
lbl_20 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 2 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_20.pack()
lbl_21 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 4', anchor = 'w', justify = tk.LEFT)
lbl_21.pack()
lbl_22 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_22.pack()
lbl_23 = tk.Label(fr_cmdInt, width = 75, text = 'After 0.0 min, Watson Marlow 1 pumps anti-clockwise at 800 RPM', anchor = 'w', justify = tk.LEFT)
lbl_23.pack()
lbl_24 = tk.Label(fr_cmdInt, width = 75, text = 'After 4.4 min, Watson Marlow 1 pumps anti-clockwise at 400 RPM', anchor = 'w', justify = tk.LEFT)
lbl_24.pack()
lbl_25 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_25.pack()
lbl_26 = tk.Label(fr_cmdInt, width = 75, text = 'After 1260 min, Valve 2 goes to position 3', anchor = 'w', justify = tk.LEFT)
lbl_26.pack()
lbl_27 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_27.pack()
lbl_28 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_28.pack()
lbl_29 = tk.Label(fr_cmdInt, width = 75, text = 'After 1 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_29.pack()
lbl_30 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 2 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_30.pack()
lbl_31 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 4', anchor = 'w', justify = tk.LEFT)
lbl_31.pack()
lbl_32 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_32.pack()
lbl_33 = tk.Label(fr_cmdInt, width = 75, text = 'After 0.0 min, Watson Marlow 1 pumps anti-clockwise at 800 RPM', anchor = 'w', justify = tk.LEFT)
lbl_33.pack()
lbl_34 = tk.Label(fr_cmdInt, width = 75, text = 'After 4.4 min, Watson Marlow 1 pumps anti-clockwise at 400 RPM', anchor = 'w', justify = tk.LEFT)
lbl_34.pack()
lbl_35 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_35.pack()
lbl_36 = tk.Label(fr_cmdInt, width = 75, text = 'After 1260 min, Valve 2 goes to position 3', anchor = 'w', justify = tk.LEFT)
lbl_36.pack()
lbl_37 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_37.pack()
lbl_38 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_38.pack()
lbl_39 = tk.Label(fr_cmdInt, width = 75, text = 'After 1 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_39.pack()
lbl_40 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 2 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_40.pack()
lbl_41 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 4', anchor = 'w', justify = tk.LEFT)
lbl_41.pack()
lbl_42 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_42.pack()
lbl_43 = tk.Label(fr_cmdInt, width = 75, text = 'After 0.0 min, Watson Marlow 1 pumps anti-clockwise at 800 RPM', anchor = 'w', justify = tk.LEFT)
lbl_43.pack()
lbl_44 = tk.Label(fr_cmdInt, width = 75, text = 'After 4.4 min, Watson Marlow 1 pumps anti-clockwise at 400 RPM', anchor = 'w', justify = tk.LEFT)
lbl_44.pack()
lbl_45 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_45.pack()
lbl_46 = tk.Label(fr_cmdInt, width = 75, text = 'After 1260 min, Valve 2 goes to position 3', anchor = 'w', justify = tk.LEFT)
lbl_46.pack()
lbl_47 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_47.pack()
lbl_48 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_48.pack()
lbl_49 = tk.Label(fr_cmdInt, width = 75, text = 'After 1 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_49.pack()
lbl_50 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 2 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_50.pack()
lbl_51 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 4', anchor = 'w', justify = tk.LEFT)
lbl_51.pack()
lbl_52 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_52.pack()
lbl_53 = tk.Label(fr_cmdInt, width = 75, text = 'After 0.0 min, Watson Marlow 1 pumps anti-clockwise at 800 RPM', anchor = 'w', justify = tk.LEFT)
lbl_53.pack()
lbl_54 = tk.Label(fr_cmdInt, width = 75, text = 'After 4.4 min, Watson Marlow 1 pumps anti-clockwise at 400 RPM', anchor = 'w', justify = tk.LEFT)
lbl_54.pack()
lbl_55 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_55.pack()
lbl_56 = tk.Label(fr_cmdInt, width = 75, text = 'After 1260 min, Valve 2 goes to position 3', anchor = 'w', justify = tk.LEFT)
lbl_56.pack()
lbl_57 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_57.pack()
lbl_58 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_58.pack()
lbl_59 = tk.Label(fr_cmdInt, width = 75, text = 'After 1 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_59.pack()
lbl_60 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 2 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_60.pack()
lbl_61 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 4', anchor = 'w', justify = tk.LEFT)
lbl_61.pack()
lbl_62 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_62.pack()
lbl_63 = tk.Label(fr_cmdInt, width = 75, text = 'After 0.0 min, Watson Marlow 1 pumps anti-clockwise at 800 RPM', anchor = 'w', justify = tk.LEFT)
lbl_63.pack()
lbl_64 = tk.Label(fr_cmdInt, width = 75, text = 'After 4.4 min, Watson Marlow 1 pumps anti-clockwise at 400 RPM', anchor = 'w', justify = tk.LEFT)
lbl_64.pack()
lbl_65 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_65.pack()
lbl_66 = tk.Label(fr_cmdInt, width = 75, text = 'After 1260 min, Valve 2 goes to position 3', anchor = 'w', justify = tk.LEFT)
lbl_66.pack()
lbl_67 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_67.pack()
lbl_68 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_68.pack()
lbl_69 = tk.Label(fr_cmdInt, width = 75, text = 'After 1 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_69.pack()
lbl_70 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 2 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_70.pack()
lbl_71 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 4', anchor = 'w', justify = tk.LEFT)
lbl_71.pack()
lbl_72 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_72.pack()
lbl_73 = tk.Label(fr_cmdInt, width = 75, text = 'After 0.0 min, Watson Marlow 1 pumps anti-clockwise at 800 RPM', anchor = 'w', justify = tk.LEFT)
lbl_73.pack()
lbl_74 = tk.Label(fr_cmdInt, width = 75, text = 'After 4.4 min, Watson Marlow 1 pumps anti-clockwise at 400 RPM', anchor = 'w', justify = tk.LEFT)
lbl_74.pack()
lbl_75 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_75.pack()
lbl_76 = tk.Label(fr_cmdInt, width = 75, text = 'After 1260 min, Valve 2 goes to position 3', anchor = 'w', justify = tk.LEFT)
lbl_76.pack()
lbl_77 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_77.pack()
lbl_78 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_78.pack()
lbl_79 = tk.Label(fr_cmdInt, width = 75, text = 'After 1 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_79.pack()
lbl_80 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 2 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_80.pack()
lbl_81 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 4', anchor = 'w', justify = tk.LEFT)
lbl_81.pack()
lbl_82 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_82.pack()
lbl_83 = tk.Label(fr_cmdInt, width = 75, text = 'After 0.0 min, Watson Marlow 1 pumps anti-clockwise at 800 RPM', anchor = 'w', justify = tk.LEFT)
lbl_83.pack()
lbl_84 = tk.Label(fr_cmdInt, width = 75, text = 'After 4.4 min, Watson Marlow 1 pumps anti-clockwise at 400 RPM', anchor = 'w', justify = tk.LEFT)
lbl_84.pack()
lbl_85 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_85.pack()
lbl_86 = tk.Label(fr_cmdInt, width = 75, text = 'After 1260 min, Valve 2 goes to position 3', anchor = 'w', justify = tk.LEFT)
lbl_86.pack()
lbl_87 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_87.pack()
lbl_88 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_88.pack()
lbl_89 = tk.Label(fr_cmdInt, width = 75, text = 'After 1 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_89.pack()
lbl_90 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 2 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_90.pack()
lbl_91 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 4', anchor = 'w', justify = tk.LEFT)
lbl_91.pack()
lbl_92 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_92.pack()
lbl_93 = tk.Label(fr_cmdInt, width = 75, text = 'After 0.0 min, Watson Marlow 1 pumps anti-clockwise at 800 RPM', anchor = 'w', justify = tk.LEFT)
lbl_93.pack()
lbl_94 = tk.Label(fr_cmdInt, width = 75, text = 'After 4.4 min, Watson Marlow 1 pumps anti-clockwise at 400 RPM', anchor = 'w', justify = tk.LEFT)
lbl_94.pack()
lbl_95 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_95.pack()
lbl_96 = tk.Label(fr_cmdInt, width = 75, text = 'After 1260 min, Valve 2 goes to position 3', anchor = 'w', justify = tk.LEFT)
lbl_96.pack()
lbl_97 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 1 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_97.pack()
lbl_98 = tk.Label(fr_cmdInt, width = 75, text = 'After 0 min, Valve 2 goes to position 1', anchor = 'w', justify = tk.LEFT)
lbl_98.pack()
lbl_99 = tk.Label(fr_cmdInt, width = 75, text = 'After 1 min, Valve 1 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_99.pack()
lbl_100 = tk.Label(fr_cmdInt, width = 75, text = 'After 5 min, Valve 2 goes to position 2', anchor = 'w', justify = tk.LEFT)
lbl_100.pack()
lbl_101 = tk.Label(fr_cmdInt, width = 75, text = 'After 5.0 min, Watson Marlow 2 stops', anchor = 'w', justify = tk.LEFT)
lbl_101.pack()
lbl_102 = tk.Label(fr_cmdInt, width = 75, text = 'After 0.0 min, Watson Marlow 1 stops', anchor = 'w', justify = tk.LEFT)
lbl_102.pack()
#endlabel
#timeline
0
0
0
4
0
0
10
5
0
1
5
5
0
0
4
0
0
10
5
0
1
5
0
0
#endtimeline
frame.btn_start['command'] =lambda:threading.Thread(target=autoprog_start, name='StartThread').start()
frame.btn_abort['command'] =lambda:threading.Thread(target=autoprog_abort, name='StartThread').start()
frame.btn_init['command'] =lambda:threading.Thread(target=autoprog_init, name='StartThread').start()
frame.window.mainloop()
